
//
//  LKAlphaComSpecs.swift
//
//  Generated by Ladislas de Toldi on 2018/10/02.
//  Copyright © 2018 Leka Inc. All rights reserved.
//

import Foundation

public let LEKA_ALPHA_COM_SPECS: String = "3.0.0"

public struct LKFrame {

    public struct start {

        public static let sequence: [UInt8] = [0x2A, 0x2B, 0x2C, 0x2D]
        public static let length: UInt8 = 4

    }

}

public struct LKCommand {

    public static let info: UInt8 = 0x70

    public struct stop {

        public static let led: UInt8 = 0xFD
        public static let motor: UInt8 = 0xFE
        public static let robot: UInt8 = 0xFF

    }

    public struct led {

        public static let id: UInt8 = 0x10

        public struct ears {

            public static let all: UInt8 = 0x11
            public static let range: UInt8 = 0x12
            public static let single: UInt8 = 0x13

        }

        public struct belt {

            public static let all: UInt8 = 0x14
            public static let range: UInt8 = 0x15
            public static let single: UInt8 = 0x16

        }

        public struct length {

            public static let all: UInt8 = 3
            public static let range: UInt8 = 1 + 1 + 3
            public static let single: UInt8 = 1 + 3

        }

    }

    public struct motor {

        public static let id: UInt8 = 0x20
        public static let all: UInt8 = 0x21
        public static let duo: UInt8 = 0x22
        public static let left: UInt8 = 0x23
        public static let right: UInt8 = 0x24

        public struct length {

            public static let all: UInt8 = 1 + 1
            public static let duo: UInt8 = 1 + 1 + 1 + 1
            public static let single: UInt8 = 1 + 1

        }

    }

    public struct motivator {

        public static let id: UInt8 = 0x50
        public static let length: UInt8 = 1
        public static let fire: UInt8 = 0x51
        public static let birds: UInt8 = 0x52
        public static let rainbow: UInt8 = 0x53
        public static let spin_blink: UInt8 = 0x54
        public static let spin_yellow: UInt8 = 0x55

    }

    public struct guidance {

        public static let id: UInt8 = 0x40
        public static let length: UInt8 = 1

        public struct translation {

            public static let left: UInt8 = 0x41
            public static let right: UInt8 = 0x42
            public static let left_right: UInt8 = 0x43
            public static let up: UInt8 = 0x44
            public static let down: UInt8 = 0x45
            public static let up_down: UInt8 = 0x46

        }

        public struct move {

            public static let away: UInt8 = 0x47
            public static let closer: UInt8 = 0x48

        }

        public struct turn {

            public static let left: UInt8 = 0x49
            public static let right: UInt8 = 0x4A

        }

        public struct tilt {

            public static let left: UInt8 = 0x4B
            public static let right: UInt8 = 0x4C
            public static let forward: UInt8 = 0x4D
            public static let backward: UInt8 = 0x4E

        }

        public struct misc {

            public static let shake: UInt8 = 0x4F

        }

    }

}
