
//
//  LKAlphaComSpecs.h
//
//  Generated by Ladislas de Toldi on 2018/10/02.
//  Copyright © 2018 Leka Inc. All rights reserved.
//

#ifndef _LEKA_ALPHA_COM_SPECS_H_
#define _LEKA_ALPHA_COM_SPECS_H_

#include <stdint.h>

using frame_t = uint8_t;


const char LEKA_ALPHA_COM_SPECS[] = "3.0.0";

namespace LKFrame {


    namespace start {

        frame_t sequence[] = {0x2A, 0x2B, 0x2C, 0x2D};
        const frame_t length = 4;

    }

}

namespace LKCommand {

    const frame_t info = 0x70;

    namespace stop {

        const frame_t led = 0xFD;
        const frame_t motor = 0xFE;
        const frame_t robot = 0xFF;

    }

    namespace led {

        const frame_t id = 0x10;

        namespace ears {

            const frame_t all = 0x11;
            const frame_t range = 0x12;
            const frame_t single = 0x13;

        }

        namespace belt {

            const frame_t all = 0x14;
            const frame_t range = 0x15;
            const frame_t single = 0x16;

        }

        namespace length {

            const frame_t all = 3;
            const frame_t range = 1 + 1 + 3;
            const frame_t single = 1 + 3;

        }

    }

    namespace motor {

        const frame_t id = 0x20;
        const frame_t all = 0x21;
        const frame_t duo = 0x22;
        const frame_t left = 0x23;
        const frame_t right = 0x24;

        namespace length {

            const frame_t all = 1 + 1;
            const frame_t duo = 1 + 1 + 1 + 1;
            const frame_t single = 1 + 1;

        }

    }

    namespace motivator {

        const frame_t id = 0x50;
        const frame_t length = 1;
        const frame_t fire = 0x51;
        const frame_t birds = 0x52;
        const frame_t rainbow = 0x53;
        const frame_t spin_blink = 0x54;
        const frame_t spin_yellow = 0x55;

    }

    namespace guidance {

        const frame_t id = 0x40;
        const frame_t length = 1;

        namespace translation {

            const frame_t left = 0x41;
            const frame_t right = 0x42;
            const frame_t left_right = 0x43;
            const frame_t up = 0x44;
            const frame_t down = 0x45;
            const frame_t up_down = 0x46;

        }

        namespace move {

            const frame_t away = 0x47;
            const frame_t closer = 0x48;

        }

        namespace turn {

            const frame_t left = 0x49;
            const frame_t right = 0x4A;

        }

        namespace tilt {

            const frame_t left = 0x4B;
            const frame_t right = 0x4C;
            const frame_t forward = 0x4D;
            const frame_t backward = 0x4E;

        }

        namespace misc {

            const frame_t shake = 0x4F;

        }

    }

}

#endif

